<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/Greeter.proto

namespace Greeter;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>greeter.SayRepeatedResponse</code>
 */
class SayRepeatedResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key = 1;</code>
     */
    private $key = '';
    /**
     * Generated from protobuf field <code>int64 value_int64 = 2;</code>
     */
    private $value_int64 = 0;

    public function __construct() {
        \GPBMetadata\Proto\Greeter::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 value_int64 = 2;</code>
     * @return int|string
     */
    public function getValueInt64()
    {
        return $this->value_int64;
    }

    /**
     * Generated from protobuf field <code>int64 value_int64 = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setValueInt64($var)
    {
        GPBUtil::checkInt64($var);
        $this->value_int64 = $var;

        return $this;
    }

}

